# Vagrant VM for locally doing docker development
Vagrant.configure(2) do |config|
  # We use Redhat Enterprise Linux 7.x to host Docker containers and
  # CentOS 7.x is the closest host OS to RHEL 7.x.
  config.vm.box = "boxcutter/centos72"
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9443, host: 9443
  config.vm.network "private_network", ip: "192.168.33.10"

  # Assumes HTRC git reporitories are cloned to same parent directory where
  # HTRC-Dockerfile is located.
  config.vm.synced_folder "../..", "/htrc/src"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end
  
  config.vm.provision :shell, path: "bootstrap.sh"
end
